@startuml Bill Web PG Purchase Process

title Bill Web PG Purchase Process

participant "Payment Market(PG)" as payment
participant "Client(Web)" as client
participant "Game Server" as game
participant "Billing Server" as bill

activate client
client -> bill : Transaction Request
activate bill 
bill -> bill : Transaction Create
bill --> client : Transaction ID Response
deactivate bill

client -> payment : PG Purchase Request
activate payment
payment -> client : Purchase Response 
deactivate payment

client -> bill : Validation Request 
activate bill
bill -> bill : Validation
bill -> payment : Receipt Info Request 
activate payment 
payment --> bill : Receipt Info Response
deactivate payment
bill -> bill : Validation Receipt
bill -> game : Give Product Request
activate game
game -> game : Give Product
game -> bill : Give Product Response
deactivate game
bill --> client : Give Product Response 
bill -> bill : Transaction End
deactivate client
deactivate bill
@enduml

