@startuml

title Bill Process

participant "Payment Market(PG, IOS,Google)" as payment
participant "Client(Web or App)" as client
participant "Game Server" as game
participant "Billing Server" as bill

group Charge Point 
client -> bill : Charge Point Request
bill -> bill : Transaction Create
bill -> bill : Validation (UserCheck, StatusCheck, Etc...) 
bill -> payment : Payment Request
payment --> bill : Response Payment 
bill -> bill : Charge Point 
bill --> Client : Charge Point  Result Response
end








@enduml
